version: '3.9'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 --workers 2 django_project.wsgi
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=123
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
  
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
